use std::fmt::Write;
use std::path::{Component, Path, PathBuf};

use crate::hash::{lowercase_hex, sha256};
use crate::model::{EnumDef, MessageKind, Presence, Primitive, Privacy, Protocol, Type};

pub const SCHEMA_HASH_TRUNCATION: &str = "sha256-first-16-bytes";
pub const GENERATOR_VERSION: &str = env!("CARGO_PKG_VERSION");

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFile {
    pub relative_path: PathBuf,
    pub contents: String,
}

pub fn generated_files(protocol: &Protocol, canonical_schema: &str) -> Vec<GeneratedFile> {
    let digest = sha256(canonical_schema.as_bytes());
    vec![
        file(
            "runtime/protocol/src/generated.rs",
            generate_rust(protocol, &digest),
        ),
        file(
            "platform/browser/generated/engine-protocol.ts",
            generate_typescript(protocol, &digest),
        ),
        file(
            "platform/desktop/generated/engine-protocol.registry",
            generate_desktop_registry(protocol, &digest),
        ),
        file(
            "protocol/generated/schema-hash.txt",
            generate_hash_registry(&digest),
        ),
        file(
            "protocol/generated/compatibility-vectors.json",
            generate_compatibility_vectors(protocol, &digest),
        ),
        file(
            "protocol/generated/invalid-vectors.json",
            generate_invalid_vectors(protocol, &digest),
        ),
    ]
}

fn file(path: &str, contents: String) -> GeneratedFile {
    GeneratedFile {
        relative_path: PathBuf::from(path),
        contents,
    }
}

pub fn write_generated(root: &Path, files: &[GeneratedFile]) -> Result<(), String> {
    for file in files {
        reject_symlink_path(root, &file.relative_path)?;
        let target = root.join(&file.relative_path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|error| format!("create {}: {error}", parent.display()))?;
        }
        reject_symlink_path(root, &file.relative_path)?;
        let temporary = target.with_extension("protocol-codegen.tmp");
        if std::fs::symlink_metadata(&temporary)
            .is_ok_and(|metadata| metadata.file_type().is_symlink())
        {
            return Err(format!(
                "refusing generated temporary symlink: {}",
                temporary.display()
            ));
        }
        std::fs::write(&temporary, file.contents.as_bytes())
            .map_err(|error| format!("write {}: {error}", temporary.display()))?;
        std::fs::rename(&temporary, &target)
            .map_err(|error| format!("replace {}: {error}", target.display()))?;
    }
    Ok(())
}

pub fn check_generated(root: &Path, files: &[GeneratedFile]) -> Result<(), Vec<PathBuf>> {
    let mut stale = Vec::new();
    for file in files {
        if reject_symlink_path(root, &file.relative_path).is_err() {
            stale.push(file.relative_path.clone());
            continue;
        }
        let target = root.join(&file.relative_path);
        match std::fs::read(&target) {
            Ok(existing) if existing == file.contents.as_bytes() => {}
            _ => stale.push(file.relative_path.clone()),
        }
    }
    if stale.is_empty() { Ok(()) } else { Err(stale) }
}

pub fn reject_symlink_path(root: &Path, relative: &Path) -> Result<(), String> {
    if relative.as_os_str().is_empty()
        || relative
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
    {
        return Err(format!(
            "generated path must be a fixed relative path: {}",
            relative.display()
        ));
    }
    if std::fs::symlink_metadata(root).is_ok_and(|metadata| metadata.file_type().is_symlink()) {
        return Err(format!(
            "repository root must not be a symlink: {}",
            root.display()
        ));
    }
    let mut candidate = root.to_path_buf();
    for component in relative.components() {
        let Component::Normal(component) = component else {
            unreachable!("component shape checked above");
        };
        candidate.push(component);
        match std::fs::symlink_metadata(&candidate) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(format!(
                    "refusing symlink in generated path: {}",
                    candidate.display()
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(format!("inspect {}: {error}", candidate.display())),
        }
    }
    Ok(())
}

fn generate_rust(protocol: &Protocol, digest: &[u8; 32]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "// @generated by pdf-rs-protocol-codegen; DO NOT EDIT."
    )
    .unwrap();
    writeln!(out, "// Source: protocol/engine.protocol").unwrap();
    writeln!(
        out,
        "// Generated declarations are documented by the canonical schema and registries."
    )
    .unwrap();
    writeln!(out, "#![allow(missing_docs)]\n").unwrap();
    writeln!(out, "pub const PROTOCOL_MAJOR: u16 = {};", protocol.major).unwrap();
    writeln!(out, "pub const PROTOCOL_MINOR: u16 = {};", protocol.minor).unwrap();
    writeln!(
        out,
        "pub const PROTOCOL_GENERATOR_VERSION: &str = \"{GENERATOR_VERSION}\";"
    )
    .unwrap();
    writeln!(
        out,
        "pub const MIN_COMPATIBLE_MINOR: u16 = {};",
        protocol.minor
    )
    .unwrap();
    writeln!(
        out,
        "pub const MAX_MESSAGE_BYTES: u32 = {};",
        protocol.max_message_bytes
    )
    .unwrap();
    writeln!(
        out,
        "pub const MAX_TRANSFER_SLOTS: u16 = {};",
        protocol.max_transfer_slots
    )
    .unwrap();
    writeln!(
        out,
        "pub const SCHEMA_SHA256: [u8; 32] = {};",
        rust_bytes(digest)
    )
    .unwrap();
    writeln!(
        out,
        "pub const SCHEMA_SHA256_HEX: &str = \"{}\";",
        lowercase_hex(digest)
    )
    .unwrap();
    writeln!(
        out,
        "pub const SCHEMA_HASH: [u8; 16] = {};",
        rust_bytes(&digest[..16])
    )
    .unwrap();
    writeln!(
        out,
        "pub const SCHEMA_HASH_TRUNCATION: &str = \"{SCHEMA_HASH_TRUNCATION}\";"
    )
    .unwrap();
    writeln!(
        out,
        "pub const DESKTOP_BYTE_ORDER: &str = \"little-endian\";"
    )
    .unwrap();
    writeln!(out, "pub const ENVELOPE_HEADER_BYTES: usize = 20;\n").unwrap();
    for record in &protocol.records {
        for field in &record.fields {
            if let Type::List(_, limit) | Type::Bytes(limit) = &field.ty {
                writeln!(
                    out,
                    "pub const {}_{}_MAX_COUNT: usize = {};",
                    screaming_snake_case(&record.name),
                    screaming_snake_case(&field.name),
                    limit
                )
                .unwrap();
            }
        }
    }
    out.push('\n');

    for scalar in &protocol.scalars {
        let rust = rust_primitive(scalar.primitive);
        if scalar.name == "PlatformHandle" {
            writeln!(
                out,
                "#[derive(Clone, Copy, Eq, Hash, Ord, PartialEq, PartialOrd)]\npub struct {}({rust});",
                scalar.name
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\npub struct {}({rust});",
                scalar.name
            )
            .unwrap();
        }
        if matches!(scalar.primitive, Primitive::Bytes16 | Primitive::Bytes32) {
            writeln!(
                out,
                "impl {} {{\n    pub const fn new(value: {rust}) -> Self {{ Self(value) }}\n    pub const fn digest(&self) -> &{rust} {{ &self.0 }}\n    pub const fn into_digest(self) -> {rust} {{ self.0 }}\n}}\n",
                scalar.name
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "impl {} {{\n    pub const fn new(value: {rust}) -> Self {{ Self(value) }}\n    pub const fn value(self) -> {rust} {{ self.0 }}\n}}\n",
                scalar.name
            )
            .unwrap();
        }
        if scalar.name == "PlatformHandle" {
            writeln!(
                out,
                "impl core::fmt::Debug for PlatformHandle {{\n    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\n        formatter.write_str(\"PlatformHandle([REDACTED])\")\n    }}\n}}\n"
            )
            .unwrap();
        }
    }

    for enumeration in &protocol.enums {
        write_rust_enum(&mut out, enumeration);
    }
    write_endpoint_capability_constants(&mut out, protocol);

    for record in &protocol.records {
        let has_redacted_field = record
            .fields
            .iter()
            .any(|field| field.privacy != Privacy::Public);
        if has_redacted_field {
            writeln!(out, "#[derive(Clone, Eq, PartialEq)]").unwrap();
        } else {
            writeln!(out, "#[derive(Clone, Debug, Eq, PartialEq)]").unwrap();
        }
        writeln!(out, "pub struct {} {{", record.name).unwrap();
        for field in &record.fields {
            writeln!(out, "    pub {}: {},", field.name, rust_type(&field.ty)).unwrap();
        }
        writeln!(out, "}}\n").unwrap();
        if has_redacted_field {
            writeln!(
                out,
                "impl core::fmt::Debug for {} {{\n    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\n        let mut output = formatter.debug_struct(\"{}\");",
                record.name, record.name
            )
            .unwrap();
            for field in &record.fields {
                if field.privacy == Privacy::Public {
                    writeln!(
                        out,
                        "        output.field(\"{}\", &self.{});",
                        field.name, field.name
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "        output.field(\"{}\", &\"[REDACTED]\");",
                        field.name
                    )
                    .unwrap();
                }
            }
            writeln!(out, "        output.finish()\n    }}\n}}\n").unwrap();
        }
    }

    for union in &protocol.unions {
        let has_redacted_field = union
            .variants
            .iter()
            .flat_map(|variant| &variant.fields)
            .any(|field| field.privacy != Privacy::Public);
        if has_redacted_field {
            writeln!(out, "#[derive(Clone, Eq, PartialEq)]").unwrap();
        } else {
            writeln!(out, "#[derive(Clone, Debug, Eq, PartialEq)]").unwrap();
        }
        writeln!(out, "pub enum {} {{", union.name).unwrap();
        for variant in &union.variants {
            if variant.fields.is_empty() {
                writeln!(out, "    {},", variant.name).unwrap();
            } else {
                writeln!(out, "    {} {{", variant.name).unwrap();
                for field in &variant.fields {
                    writeln!(out, "        {}: {},", field.name, rust_type(&field.ty)).unwrap();
                }
                writeln!(out, "    }},").unwrap();
            }
        }
        writeln!(out, "}}\n").unwrap();
        if has_redacted_field {
            writeln!(
                out,
                "impl core::fmt::Debug for {} {{\n    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\n        formatter.write_str(\"{}([REDACTED])\")\n    }}\n}}\n",
                union.name, union.name
            )
            .unwrap();
        }
    }

    write_message_enums(&mut out, protocol);
    write_descriptors(&mut out, protocol);
    write_capability_decision_invariants(&mut out);
    out
}

fn write_rust_enum(out: &mut String, enumeration: &EnumDef) {
    writeln!(
        out,
        "#[repr({})]\n#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]",
        rust_primitive(enumeration.repr)
    )
    .unwrap();
    writeln!(out, "pub enum {} {{", enumeration.name).unwrap();
    for variant in &enumeration.variants {
        writeln!(out, "    {} = {},", variant.name, variant.tag).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
}

fn write_endpoint_capability_constants(out: &mut String, protocol: &Protocol) {
    let Some(capabilities) = protocol
        .enums
        .iter()
        .find(|value| value.name == "EndpointCapability")
    else {
        return;
    };
    let mut expression = Vec::new();
    for variant in &capabilities.variants {
        let constant = format!(
            "ENDPOINT_CAPABILITY_{}",
            screaming_snake_case(&variant.name)
        );
        writeln!(
            out,
            "pub const {constant}: u64 = EndpointCapability::{} as u64;",
            variant.name
        )
        .unwrap();
        expression.push(constant);
    }
    writeln!(
        out,
        "pub const KNOWN_ENDPOINT_CAPABILITIES: u64 = {};",
        expression.join(" | ")
    )
    .unwrap();
    writeln!(
        out,
        "pub const ENGINE_SUPPORTED_ENDPOINT_CAPABILITIES: u64 = KNOWN_ENDPOINT_CAPABILITIES;\n"
    )
    .unwrap();
}

fn write_message_enums(out: &mut String, protocol: &Protocol) {
    for (kind, name) in [
        (MessageKind::Command, "Command"),
        (MessageKind::Event, "Event"),
    ] {
        writeln!(out, "#[derive(Clone, Debug, Eq, PartialEq)]").unwrap();
        writeln!(out, "pub enum {name} {{").unwrap();
        for message in protocol
            .messages
            .iter()
            .filter(|message| message.kind == kind)
        {
            writeln!(out, "    {}({}),", message.name, message.payload).unwrap();
        }
        writeln!(out, "}}\n").unwrap();
    }
    writeln!(
        out,
        "#[derive(Clone, Debug, Eq, PartialEq)]\npub struct CommandEnvelope {{\n    pub header: EnvelopeHeader,\n    pub correlation: Correlation,\n    pub command: Command,\n}}\n"
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Clone, Debug, Eq, PartialEq)]\npub struct EventEnvelope {{\n    pub header: EnvelopeHeader,\n    pub correlation: Correlation,\n    pub event: Event,\n}}\n"
    )
    .unwrap();
}

fn write_descriptors(out: &mut String, protocol: &Protocol) {
    for message in &protocol.messages {
        writeln!(
            out,
            "pub const MESSAGE_ID_{}: u16 = {};",
            screaming_snake_case(&message.name),
            message.id
        )
        .unwrap();
    }
    out.push('\n');
    out.push_str(
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
pub enum MessageKind { Command, Event }\n\n\
#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
pub enum CorrelationRequirement { Required, Optional, Forbidden }\n\n\
#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
pub struct CorrelationShape {\n\
    pub worker: CorrelationRequirement,\n\
    pub session: CorrelationRequirement,\n\
    pub request: CorrelationRequirement,\n\
    pub generation: CorrelationRequirement,\n\
}\n\n\
#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
pub enum FieldPrivacy { Public, Private, Sensitive }\n\n\
#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
pub struct FieldDescriptor {\n\
    pub name: &'static str,\n\
    pub wire_type: &'static str,\n\
    pub required: bool,\n\
    pub privacy: FieldPrivacy,\n\
    pub max_count: u32,\n\
}\n\n\
#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
pub struct MessageDescriptor {\n\
    pub kind: MessageKind,\n\
    pub name: &'static str,\n\
    pub id: u16,\n\
    pub payload: &'static str,\n\
    pub state: &'static str,\n\
    pub correlation: &'static str,\n\
    pub correlation_shape: CorrelationShape,\n\
    pub replayable: bool,\n\
    pub terminal: bool,\n\
    pub allowed_flags: u16,\n\
    pub min_transfer_slots: u16,\n\
    pub max_transfer_slots: u16,\n\
    pub max_payload_bytes: u32,\n\
    pub fields: &'static [FieldDescriptor],\n\
    pub outcome_events: &'static [u16],\n\
}\n\n",
    );

    for message in &protocol.messages {
        let record = protocol
            .records
            .iter()
            .find(|record| record.name == message.payload)
            .expect("parser validates payload type");
        writeln!(
            out,
            "const {}_FIELDS: &[FieldDescriptor] = &[",
            screaming_snake_case(&message.name)
        )
        .unwrap();
        for field in &record.fields {
            writeln!(
                out,
                "    FieldDescriptor {{ name: \"{}\", wire_type: \"{}\", required: {}, privacy: FieldPrivacy::{}, max_count: {} }},",
                field.name,
                field.ty.schema_name(),
                field.presence == Presence::Required,
                rust_privacy(field.privacy),
                type_limit(&field.ty)
            )
            .unwrap();
        }
        writeln!(out, "];").unwrap();
        if message.kind == MessageKind::Command {
            let ids = message
                .outcomes
                .iter()
                .map(|outcome| {
                    protocol
                        .messages
                        .iter()
                        .find(|candidate| {
                            candidate.kind == MessageKind::Event && candidate.name == *outcome
                        })
                        .expect("parser validates outcomes")
                        .id
                        .to_string()
                })
                .collect::<Vec<_>>();
            writeln!(
                out,
                "const {}_OUTCOME_EVENTS: &[u16] = &[{}];",
                screaming_snake_case(&message.name),
                ids.join(", ")
            )
            .unwrap();
        }
    }
    out.push('\n');

    for (kind, constant) in [
        (MessageKind::Command, "COMMAND_DESCRIPTORS"),
        (MessageKind::Event, "EVENT_DESCRIPTORS"),
    ] {
        writeln!(out, "pub const {constant}: &[MessageDescriptor] = &[").unwrap();
        for message in protocol
            .messages
            .iter()
            .filter(|message| message.kind == kind)
        {
            let prefix = screaming_snake_case(&message.name);
            let outcome_events = if kind == MessageKind::Command {
                format!("{prefix}_OUTCOME_EVENTS")
            } else {
                "&[]".into()
            };
            let (worker, session, request, generation) = correlation_shape(&message.correlation);
            writeln!(
                out,
                "    MessageDescriptor {{ kind: MessageKind::{}, name: \"{}\", id: {}, payload: \"{}\", state: \"{}\", correlation: \"{}\", correlation_shape: CorrelationShape {{ worker: CorrelationRequirement::{worker}, session: CorrelationRequirement::{session}, request: CorrelationRequirement::{request}, generation: CorrelationRequirement::{generation} }}, replayable: {}, terminal: {}, allowed_flags: {}, min_transfer_slots: {}, max_transfer_slots: {}, max_payload_bytes: {}, fields: {prefix}_FIELDS, outcome_events: {outcome_events} }},",
                if kind == MessageKind::Command { "Command" } else { "Event" },
                message.name,
                message.id,
                message.payload,
                message.state,
                message.correlation,
                message.disposition == "yes",
                message.disposition == "terminal",
                message.allowed_flags,
                message.min_transfer_slots,
                message.max_transfer_slots,
                message.max_payload_bytes
            )
            .unwrap();
        }
        writeln!(out, "];\n").unwrap();
    }
    out.push_str(
        "pub fn descriptor_by_id(id: u16) -> Option<&'static MessageDescriptor> {\n\
    COMMAND_DESCRIPTORS.iter().chain(EVENT_DESCRIPTORS.iter()).find(|value| value.id == id)\n\
}\n\n",
    );
}

fn write_capability_decision_invariants(out: &mut String) {
    out.push_str(
        "impl CapabilityDecision {\n\
    /// Checks bounded-list accounting and status-dependent wire invariants.\n\
    pub fn wire_invariants_valid(&self) -> bool {\n\
        let missing_len = u32::try_from(self.missing.len()).ok();\n\
        let contributors_len = u32::try_from(self.contributors.len()).ok();\n\
        let missing_accounted = match self.missing_completeness {\n\
            CollectionCompleteness::Complete => missing_len == Some(self.missing_total),\n\
            CollectionCompleteness::Truncated => missing_len.is_some_and(|len| len < self.missing_total),\n\
        };\n\
        let contributors_accounted = match self.contributors_completeness {\n\
            CollectionCompleteness::Complete => contributors_len == Some(self.contributors_total),\n\
            CollectionCompleteness::Truncated => contributors_len.is_some_and(|len| len < self.contributors_total),\n\
        };\n\
        let status_valid = match self.status {\n\
            SupportStatus::Supported => self.missing_total == 0\n\
                && self.missing.is_empty()\n\
                && self.location.is_none()\n\
                && self.rejection_code.is_none(),\n\
            SupportStatus::Unsupported => self.rejection_code.is_none(),\n\
            SupportStatus::Rejected => self.rejection_code.is_some(),\n\
        };\n\
        missing_accounted && contributors_accounted && status_valid\n\
    }\n\
}\n",
    );
}

fn rust_primitive(value: Primitive) -> &'static str {
    match value {
        Primitive::U8 => "u8",
        Primitive::U16 => "u16",
        Primitive::U32 => "u32",
        Primitive::U64 => "u64",
        Primitive::I32 => "i32",
        Primitive::Bool => "bool",
        Primitive::Bytes16 => "[u8; 16]",
        Primitive::Bytes32 => "[u8; 32]",
    }
}

fn rust_type(value: &Type) -> String {
    match value {
        Type::Primitive(value) => rust_primitive(*value).into(),
        Type::Named(value) => value.clone(),
        Type::Optional(inner) => format!("Option<{}>", rust_type(inner)),
        Type::List(inner, _) => format!("Vec<{}>", rust_type(inner)),
        Type::Bytes(_) => "Vec<u8>".into(),
    }
}

fn rust_privacy(value: Privacy) -> &'static str {
    match value {
        Privacy::Public => "Public",
        Privacy::Private => "Private",
        Privacy::Sensitive => "Sensitive",
    }
}

fn type_limit(value: &Type) -> u32 {
    match value {
        Type::List(_, limit) | Type::Bytes(limit) => *limit,
        Type::Optional(inner) => type_limit(inner),
        _ => 0,
    }
}

fn correlation_shape(value: &str) -> (&'static str, &'static str, &'static str, &'static str) {
    match value {
        "Worker" => ("Required", "Forbidden", "Forbidden", "Forbidden"),
        "Session" => ("Required", "Required", "Forbidden", "Forbidden"),
        "Request" => ("Required", "Optional", "Required", "Forbidden"),
        "Generation" => ("Required", "Required", "Forbidden", "Required"),
        other => panic!("unknown validated correlation shape {other}"),
    }
}

fn rust_bytes(bytes: &[u8]) -> String {
    let values = bytes
        .iter()
        .map(|value| format!("0x{value:02x}"))
        .collect::<Vec<_>>();
    format!("[{}]", values.join(", "))
}

fn screaming_snake_case(value: &str) -> String {
    let mut output = String::new();
    for (index, byte) in value.bytes().enumerate() {
        if byte.is_ascii_uppercase() && index != 0 {
            output.push('_');
        }
        output.push((byte as char).to_ascii_uppercase());
    }
    output
}

fn generate_typescript(protocol: &Protocol, digest: &[u8; 32]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "// @generated by pdf-rs-protocol-codegen; DO NOT EDIT."
    )
    .unwrap();
    writeln!(
        out,
        "export const PROTOCOL_MAJOR = {} as const;",
        protocol.major
    )
    .unwrap();
    writeln!(
        out,
        "export const PROTOCOL_MINOR = {} as const;",
        protocol.minor
    )
    .unwrap();
    writeln!(
        out,
        "export const PROTOCOL_GENERATOR_VERSION = \"{GENERATOR_VERSION}\" as const;"
    )
    .unwrap();
    writeln!(
        out,
        "export const MIN_COMPATIBLE_MINOR = {} as const;",
        protocol.minor
    )
    .unwrap();
    writeln!(
        out,
        "export const MAX_MESSAGE_BYTES = {} as const;",
        protocol.max_message_bytes
    )
    .unwrap();
    writeln!(
        out,
        "export const MAX_TRANSFER_SLOTS = {} as const;",
        protocol.max_transfer_slots
    )
    .unwrap();
    writeln!(
        out,
        "export const SCHEMA_SHA256_HEX = \"{}\" as const;",
        lowercase_hex(digest)
    )
    .unwrap();
    writeln!(
        out,
        "export const SCHEMA_HASH_HEX = \"{}\" as const;",
        lowercase_hex(&digest[..16])
    )
    .unwrap();
    writeln!(
        out,
        "export const SCHEMA_HASH_TRUNCATION = \"{SCHEMA_HASH_TRUNCATION}\" as const;\n"
    )
    .unwrap();
    out.push_str(
        "// Validators reject unknown payload keys. Encoders must target the negotiated minor;\n\
// compatibility is never implemented by silently accepting an unversioned extension field.\n\
export const UNKNOWN_PAYLOAD_FIELD_POLICY = \"reject\" as const;\n\n",
    );
    write_ts_helpers(&mut out);

    for scalar in &protocol.scalars {
        writeln!(
            out,
            "export type {} = {};\nexport const validate{} = (value: unknown): value is {} => {};\n",
            scalar.name,
            ts_primitive(scalar.primitive),
            scalar.name,
            scalar.name,
            ts_primitive_validator(scalar.primitive, "value")
        )
        .unwrap();
    }
    for enumeration in &protocol.enums {
        write_ts_enum(&mut out, enumeration);
    }
    write_ts_endpoint_capabilities(&mut out, protocol);
    write_ts_descriptors(&mut out, protocol);
    for record in &protocol.records {
        write_ts_record(&mut out, record);
    }
    for union in &protocol.unions {
        writeln!(out, "export type {} =", union.name).unwrap();
        for variant in &union.variants {
            write!(out, "  | {{ kind: \"{}\"", variant.name).unwrap();
            for field in &variant.fields {
                write!(out, "; {}: {}", field.name, ts_type(&field.ty)).unwrap();
            }
            writeln!(out, " }}").unwrap();
        }
        writeln!(out, ";\n").unwrap();
        writeln!(
            out,
            "export function validate{}(value: unknown): value is {} {{",
            union.name, union.name
        )
        .unwrap();
        writeln!(
            out,
            "  if (!isRecord(value) || typeof value.kind !== \"string\") return false;"
        )
        .unwrap();
        writeln!(out, "  switch (value.kind) {{").unwrap();
        for variant in &union.variants {
            let required = std::iter::once("kind")
                .chain(variant.fields.iter().map(|field| field.name.as_str()))
                .map(|name| format!("\"{name}\""))
                .collect::<Vec<_>>()
                .join(", ");
            write!(
                out,
                "    case \"{}\": return exactKeys(value, [{required}], [])",
                variant.name
            )
            .unwrap();
            for field in &variant.fields {
                write!(
                    out,
                    " && {}",
                    ts_validator(&field.ty, &format!("value.{}", field.name))
                )
                .unwrap();
            }
            writeln!(out, ";").unwrap();
        }
        writeln!(out, "    default: return false;\n  }}\n}}\n").unwrap();
    }
    write_ts_messages(&mut out, protocol);
    out
}

fn write_ts_helpers(out: &mut String) {
    out.push_str(
        "type UnknownRecord = Record<string, unknown>;\n\
const hasOwn = (value: UnknownRecord, key: string): boolean => Object.prototype.hasOwnProperty.call(value, key);\n\
const isRecord = (value: unknown): value is UnknownRecord => typeof value === \"object\" && value !== null && !Array.isArray(value);\n\
const exactKeys = (value: UnknownRecord, required: readonly string[], optional: readonly string[]): boolean => {\n\
  const allowed = new Set([...required, ...optional]);\n\
  return required.every((key) => hasOwn(value, key)) && Object.keys(value).every((key) => allowed.has(key));\n\
};\n\
const isU8 = (value: unknown): value is number => Number.isInteger(value) && Number(value) >= 0 && Number(value) <= 0xff;\n\
const isU16 = (value: unknown): value is number => Number.isInteger(value) && Number(value) >= 0 && Number(value) <= 0xffff;\n\
const isU32 = (value: unknown): value is number => Number.isInteger(value) && Number(value) >= 0 && Number(value) <= 0xffffffff;\n\
const isI32 = (value: unknown): value is number => Number.isInteger(value) && Number(value) >= -0x80000000 && Number(value) <= 0x7fffffff;\n\
const isU64 = (value: unknown): value is bigint => typeof value === \"bigint\" && value >= 0n && value <= 0xffffffffffffffffn;\n\
const isFixedBytes = (value: unknown, length: number): value is Uint8Array => value instanceof Uint8Array && value.byteLength === length;\n\
const gcdU32 = (left: number, right: number): number => {\n\
  let a = left;\n\
  let b = right;\n\
  while (b !== 0) {\n\
    const remainder = a % b;\n\
    a = b;\n\
    b = remainder;\n\
  }\n\
  return a;\n\
};\n\n",
    );
}

fn write_ts_enum(out: &mut String, enumeration: &EnumDef) {
    if enumeration.repr == Primitive::U64 {
        writeln!(out, "export const {} = {{", enumeration.name).unwrap();
        for variant in &enumeration.variants {
            writeln!(out, "  {}: {}n,", variant.name, variant.tag).unwrap();
        }
        writeln!(
            out,
            "}} as const;\nexport type {} = (typeof {})[keyof typeof {}];",
            enumeration.name, enumeration.name, enumeration.name
        )
        .unwrap();
    } else {
        writeln!(out, "export enum {} {{", enumeration.name).unwrap();
        for variant in &enumeration.variants {
            writeln!(out, "  {} = {},", variant.name, variant.tag).unwrap();
        }
        writeln!(out, "}}").unwrap();
    }
    let values = enumeration
        .variants
        .iter()
        .map(|variant| {
            if enumeration.repr == Primitive::U64 {
                format!("{}n", variant.tag)
            } else {
                variant.tag.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "export const validate{} = (value: unknown): value is {} => [{}].includes(value as never);\n",
        enumeration.name, enumeration.name, values
    )
    .unwrap();
}

fn write_ts_endpoint_capabilities(out: &mut String, protocol: &Protocol) {
    let Some(definition) = protocol
        .enums
        .iter()
        .find(|value| value.name == "EndpointCapability")
    else {
        return;
    };
    for variant in &definition.variants {
        writeln!(
            out,
            "export const ENDPOINT_CAPABILITY_{} = {}n as const;",
            screaming_snake_case(&variant.name),
            variant.tag
        )
        .unwrap();
    }
    let expression = definition
        .variants
        .iter()
        .map(|variant| format!("{}n", variant.tag))
        .collect::<Vec<_>>()
        .join(" | ");
    writeln!(
        out,
        "export const KNOWN_ENDPOINT_CAPABILITIES = {expression};\nexport const ENGINE_SUPPORTED_ENDPOINT_CAPABILITIES = KNOWN_ENDPOINT_CAPABILITIES;\n"
    )
    .unwrap();
}

fn write_ts_descriptors(out: &mut String, protocol: &Protocol) {
    out.push_str(
        "export type MessageKind = \"command\" | \"event\";\n\
export type CorrelationRequirement = \"required\" | \"optional\" | \"forbidden\";\n\
export interface CorrelationShape {\n\
  readonly worker: CorrelationRequirement;\n\
  readonly session: CorrelationRequirement;\n\
  readonly request: CorrelationRequirement;\n\
  readonly generation: CorrelationRequirement;\n\
}\n\
export interface MessageDescriptor {\n\
  readonly kind: MessageKind;\n\
  readonly name: string;\n\
  readonly id: number;\n\
  readonly payload: string;\n\
  readonly state: string;\n\
  readonly correlation: string;\n\
  readonly correlation_shape: CorrelationShape;\n\
  readonly replayable: boolean;\n\
  readonly terminal: boolean;\n\
  readonly allowed_flags: number;\n\
  readonly min_transfer_slots: number;\n\
  readonly max_transfer_slots: number;\n\
  readonly max_payload_bytes: number;\n\
  readonly outcome_events: readonly number[];\n\
}\n\n",
    );
    for message in &protocol.messages {
        writeln!(
            out,
            "export const MESSAGE_ID_{} = {} as const;",
            screaming_snake_case(&message.name),
            message.id
        )
        .unwrap();
    }
    out.push_str("\nexport const MESSAGE_DESCRIPTORS = [\n");
    for message in &protocol.messages {
        let (worker, session, request, generation) = correlation_shape(&message.correlation);
        let outcomes = message
            .outcomes
            .iter()
            .map(|outcome| {
                protocol
                    .messages
                    .iter()
                    .find(|candidate| {
                        candidate.kind == MessageKind::Event && candidate.name == *outcome
                    })
                    .expect("parser validates outcomes")
                    .id
                    .to_string()
            })
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            out,
            "  {{ kind: \"{}\", name: \"{}\", id: {}, payload: \"{}\", state: \"{}\", correlation: \"{}\", correlation_shape: {{ worker: \"{}\", session: \"{}\", request: \"{}\", generation: \"{}\" }}, replayable: {}, terminal: {}, allowed_flags: {}, min_transfer_slots: {}, max_transfer_slots: {}, max_payload_bytes: {}, outcome_events: [{}] }},",
            message.kind.schema_name(),
            message.name,
            message.id,
            message.payload,
            message.state,
            message.correlation,
            worker.to_ascii_lowercase(),
            session.to_ascii_lowercase(),
            request.to_ascii_lowercase(),
            generation.to_ascii_lowercase(),
            message.disposition == "yes",
            message.disposition == "terminal",
            message.allowed_flags,
            message.min_transfer_slots,
            message.max_transfer_slots,
            message.max_payload_bytes,
            outcomes
        )
        .unwrap();
    }
    out.push_str(
        "] as const satisfies readonly MessageDescriptor[];\n\
const MESSAGE_DESCRIPTOR_BY_ID: ReadonlyMap<number, MessageDescriptor> = new Map(MESSAGE_DESCRIPTORS.map((descriptor) => [descriptor.id, descriptor] as const));\n\
export const descriptorById = (id: number): MessageDescriptor | undefined => MESSAGE_DESCRIPTOR_BY_ID.get(id);\n\n",
    );
}

fn write_ts_record(out: &mut String, record: &crate::model::Record) {
    writeln!(out, "export interface {} {{", record.name).unwrap();
    for field in &record.fields {
        let marker = if field.presence == Presence::Optional {
            "?"
        } else {
            ""
        };
        writeln!(out, "  {}{}: {};", field.name, marker, ts_type(&field.ty)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    let required = record
        .fields
        .iter()
        .filter(|field| field.presence == Presence::Required)
        .map(|field| format!("\"{}\"", field.name))
        .collect::<Vec<_>>()
        .join(", ");
    let optional = record
        .fields
        .iter()
        .filter(|field| field.presence == Presence::Optional)
        .map(|field| format!("\"{}\"", field.name))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "export function validate{}(value: unknown): value is {} {{",
        record.name, record.name
    )
    .unwrap();
    writeln!(
        out,
        "  if (!isRecord(value) || !exactKeys(value, [{required}], [{optional}])) return false;"
    )
    .unwrap();
    for field in &record.fields {
        let condition = ts_validator(&field.ty, &format!("value.{}", field.name));
        if field.presence == Presence::Optional {
            writeln!(
                out,
                "  if (hasOwn(value, \"{}\") && !({condition})) return false;",
                field.name
            )
            .unwrap();
        } else {
            writeln!(out, "  if (!({condition})) return false;").unwrap();
        }
    }
    if record.name == "EnvelopeHeader" {
        out.push_str(
            "  const header = value as unknown as EnvelopeHeader;\n\
  const descriptor = descriptorById(header.message_type);\n\
  if (descriptor === undefined) return false;\n\
  if (header.major !== PROTOCOL_MAJOR || header.minor < MIN_COMPATIBLE_MINOR || header.minor > PROTOCOL_MINOR) return false;\n\
  if ((header.flags & ~descriptor.allowed_flags) !== 0) return false;\n\
  if (header.payload_len > MAX_MESSAGE_BYTES || header.payload_len > descriptor.max_payload_bytes) return false;\n\
  if (header.sequence === 0n) return false;\n",
        );
    }
    if record.name == "EndpointCapabilities" {
        out.push_str(
            "  const capabilities = value as unknown as EndpointCapabilities;\n\
  if ((capabilities.mandatory & ~KNOWN_ENDPOINT_CAPABILITIES) !== 0n) return false;\n\
  if ((capabilities.mandatory & ~capabilities.supported) !== 0n) return false;\n",
        );
    }
    if record.name == "ProtocolHello" {
        out.push_str(
            "  const hello = value as unknown as ProtocolHello;\n\
  if (hello.major !== PROTOCOL_MAJOR || hello.minor < MIN_COMPATIBLE_MINOR || hello.minor > PROTOCOL_MINOR) return false;\n\
  if (hello.max_message_bytes === 0 || hello.max_message_bytes > MAX_MESSAGE_BYTES) return false;\n\
  if (hello.max_transfer_slots === 0 || hello.max_transfer_slots > MAX_TRANSFER_SLOTS) return false;\n",
        );
    }
    if record.name == "PageGeometry" {
        out.push_str(
            "  const geometry = value as unknown as PageGeometry;\n\
  if (!geometry.identity.some((byte) => byte !== 0)) return false;\n\
  if (geometry.media_box_width_milli_points === 0 || geometry.media_box_height_milli_points === 0 || geometry.crop_box_width_milli_points === 0 || geometry.crop_box_height_milli_points === 0) return false;\n",
        );
    }
    if record.name == "PageViewport" {
        out.push_str(
            "  const page = value as unknown as PageViewport;\n\
  if (page.clip_width_milli_points === 0 || page.clip_height_milli_points === 0) return false;\n",
        );
    }
    if record.name == "ViewportRequest" {
        out.push_str(
            "  const viewport = value as unknown as ViewportRequest;\n\
  if (viewport.generation === 0n || viewport.document_revision === 0n || viewport.zoom_numerator === 0 || viewport.zoom_denominator === 0 || viewport.device_scale_milli === 0) return false;\n\
  if (gcdU32(viewport.zoom_numerator, viewport.zoom_denominator) !== 1) return false;\n\
  const pageIndexes = new Set(viewport.visible_pages.map((page) => page.page_index));\n\
  if (pageIndexes.size !== viewport.visible_pages.length) return false;\n\
  const pageIdentities = new Set(viewport.visible_pages.map((page) => Array.from(page.geometry.identity).join(\",\")));\n\
  if (pageIdentities.size !== viewport.visible_pages.length) return false;\n",
        );
    }
    if record.name == "CapabilityDecision" {
        out.push_str(
            "  const decision = value as unknown as CapabilityDecision;\n\
  const missingCount = decision.missing.length;\n\
  const contributorCount = decision.contributors.length;\n\
  if (decision.missing_completeness === CollectionCompleteness.Complete ? missingCount !== decision.missing_total : missingCount >= decision.missing_total) return false;\n\
  if (decision.contributors_completeness === CollectionCompleteness.Complete ? contributorCount !== decision.contributors_total : contributorCount >= decision.contributors_total) return false;\n\
  if (decision.status === SupportStatus.Supported && (decision.missing_total !== 0 || missingCount !== 0 || hasOwn(value, \"location\") || hasOwn(value, \"rejection_code\"))) return false;\n\
  if (decision.status === SupportStatus.Unsupported && hasOwn(value, \"rejection_code\")) return false;\n\
  if (decision.status === SupportStatus.Rejected && !hasOwn(value, \"rejection_code\")) return false;\n",
        );
    }
    if record.name == "SurfaceReadyEvent" {
        out.push_str(
            "  const surface = value as unknown as SurfaceReadyEvent;\n\
  const metadata = surface.metadata;\n\
  if (metadata.id === 0n || metadata.owner.worker === 0n || metadata.owner.session === 0n || metadata.generation === 0n || metadata.renderer_epoch === 0 || metadata.plan_id === 0n) return false;\n\
  if (!metadata.render_config.some((byte) => byte !== 0) || !metadata.plan_hash.some((byte) => byte !== 0) || !metadata.scene_hash.some((byte) => byte !== 0) || !metadata.decision_hash.some((byte) => byte !== 0)) return false;\n\
  if (metadata.width === 0 || metadata.height === 0 || metadata.stride === 0 || metadata.region.width === 0 || metadata.region.height === 0) return false;\n\
  const stride = BigInt(metadata.stride);\n\
  const minimumStride = BigInt(metadata.width) * 4n;\n\
  if (stride < minimumStride || stride % 4n !== 0n) return false;\n\
  const layoutBytes = stride * BigInt(metadata.height);\n\
  if (metadata.byte_length !== layoutBytes) return false;\n\
  const rangeEnd = metadata.byte_offset + metadata.byte_length;\n\
  if (rangeEnd > 0xffffffffffffffffn) return false;\n\
  let regionLength: bigint;\n\
  switch (surface.transport.kind) {\n\
    case \"OffscreenCanvasCommit\": if (surface.transport.canvas === 0n) return false; regionLength = surface.transport.region_length; break;\n\
    case \"BrowserTransfer\": regionLength = surface.transport.transfer_length; break;\n\
    case \"SharedMemory\": if (surface.transport.handle === 0n || surface.transport.release_token === 0n) return false; regionLength = surface.transport.region_length; break;\n\
    case \"LocalMemory\": if (surface.transport.memory_epoch === 0) return false; regionLength = surface.transport.region_length; break;\n\
  }\n\
  if (rangeEnd > regionLength) return false;\n",
        );
    }
    writeln!(out, "  return true;\n}}\n").unwrap();
}

fn write_ts_messages(out: &mut String, protocol: &Protocol) {
    for (kind, name) in [
        (MessageKind::Command, "Command"),
        (MessageKind::Event, "Event"),
    ] {
        writeln!(out, "export type {name} =").unwrap();
        for message in protocol
            .messages
            .iter()
            .filter(|message| message.kind == kind)
        {
            writeln!(
                out,
                "  | {{ type: \"{}\"; payload: {} }}",
                message.name, message.payload
            )
            .unwrap();
        }
        writeln!(out, ";\n").unwrap();
        writeln!(
            out,
            "export function validate{name}(value: unknown): value is {name} {{\n  if (!isRecord(value) || !exactKeys(value, [\"type\", \"payload\"], []) || typeof value.type !== \"string\") return false;\n  switch (value.type) {{"
        )
        .unwrap();
        for message in protocol
            .messages
            .iter()
            .filter(|message| message.kind == kind)
        {
            writeln!(
                out,
                "    case \"{}\": return validate{}(value.payload);",
                message.name, message.payload
            )
            .unwrap();
        }
        writeln!(out, "    default: return false;\n  }}\n}}\n").unwrap();
    }
    out.push_str(
        "export interface CommandEnvelope { header: EnvelopeHeader; correlation: Correlation; command: Command }\n\
export interface EventEnvelope { header: EnvelopeHeader; correlation: Correlation; event: Event }\n\n\
const correlationRequirementMet = (present: boolean, requirement: CorrelationRequirement): boolean => requirement === \"required\" ? present : requirement === \"optional\" ? true : !present;\n\
const validateDescriptorCorrelation = (correlation: Correlation, descriptor: MessageDescriptor): boolean => {\n\
  if (correlation.worker === 0n || correlation.session === 0n || correlation.request === 0n || correlation.generation === 0n) return false;\n\
  return correlationRequirementMet(true, descriptor.correlation_shape.worker)\n\
    && correlationRequirementMet(correlation.session !== undefined, descriptor.correlation_shape.session)\n\
    && correlationRequirementMet(correlation.request !== undefined, descriptor.correlation_shape.request)\n\
    && correlationRequirementMet(correlation.generation !== undefined, descriptor.correlation_shape.generation);\n\
};\n\
const validateTransferBinding = (message: Command | Event, transferSlots: number, descriptor: MessageDescriptor): boolean => {\n\
  if (!isU16(transferSlots) || transferSlots > MAX_TRANSFER_SLOTS || transferSlots < descriptor.min_transfer_slots || transferSlots > descriptor.max_transfer_slots) return false;\n\
  switch (message.type) {\n\
    case \"ProvideData\": return message.payload.segments.length === transferSlots && message.payload.segments.every((segment, index) => segment.slot === index);\n\
    case \"RegisterCanvas\": return message.payload.transfer_slot < transferSlots;\n\
    case \"SurfaceReady\": {\n\
      const transport = message.payload.transport;\n\
      switch (transport.kind) {\n\
        case \"BrowserTransfer\": return transferSlots === 1 && transport.slot < transferSlots;\n\
        case \"SharedMemory\": return transferSlots === 1;\n\
        case \"OffscreenCanvasCommit\":\n\
        case \"LocalMemory\": return transferSlots === 0;\n\
      }\n\
    }\n\
    default: return true;\n\
  }\n\
};\n\
const validatePayloadCorrelation = (correlation: Correlation, message: Command | Event): boolean => {\n\
  switch (message.type) {\n\
    case \"SetViewport\": return correlation.generation === message.payload.viewport.generation;\n\
    case \"Cancel\": return correlation.request === message.payload.target;\n\
    case \"Ready\": return correlation.worker === message.payload.worker;\n\
    case \"DocumentReady\": return correlation.session === undefined || correlation.session === message.payload.session;\n\
    case \"SurfaceReady\": return correlation.worker === message.payload.metadata.owner.worker\n\
      && correlation.session === message.payload.metadata.owner.session\n\
      && correlation.generation === message.payload.metadata.generation;\n\
    case \"RequestCancelled\": return correlation.request === message.payload.target;\n\
    case \"SessionClosed\": return correlation.session === message.payload.session;\n\
    case \"WorkerStopped\": return correlation.worker === message.payload.worker;\n\
    default: return true;\n\
  }\n\
};\n\
const validateEnvelopeDescriptor = (header: EnvelopeHeader, correlation: Correlation, message: Command | Event, kind: MessageKind, transferSlots: number): boolean => {\n\
  const descriptor = descriptorById(header.message_type);\n\
  return descriptor !== undefined\n\
    && descriptor.kind === kind\n\
    && descriptor.name === message.type\n\
    && validateDescriptorCorrelation(correlation, descriptor)\n\
    && validateTransferBinding(message, transferSlots, descriptor)\n\
    && validatePayloadCorrelation(correlation, message);\n\
};\n\
export function validateEnvelopeHeaderForMinor(value: unknown, negotiatedMinor: number): value is EnvelopeHeader {\n\
  return Number.isInteger(negotiatedMinor)\n\
    && negotiatedMinor >= MIN_COMPATIBLE_MINOR\n\
    && negotiatedMinor <= PROTOCOL_MINOR\n\
    && validateEnvelopeHeader(value)\n\
    && value.minor === negotiatedMinor;\n\
}\n\
export function validateCommandEnvelope(value: unknown, transferSlots = 0, negotiatedMinor: number = PROTOCOL_MINOR): value is CommandEnvelope {\n\
  if (!isRecord(value) || !exactKeys(value, [\"header\", \"correlation\", \"command\"], []) || !validateEnvelopeHeaderForMinor(value.header, negotiatedMinor) || !validateCorrelation(value.correlation) || !validateCommand(value.command)) return false;\n\
  const envelope = value as unknown as CommandEnvelope;\n\
  return validateEnvelopeDescriptor(envelope.header, envelope.correlation, envelope.command, \"command\", transferSlots);\n\
}\n\
export function validateEventEnvelope(value: unknown, transferSlots = 0, negotiatedMinor: number = PROTOCOL_MINOR): value is EventEnvelope {\n\
  if (!isRecord(value) || !exactKeys(value, [\"header\", \"correlation\", \"event\"], []) || !validateEnvelopeHeaderForMinor(value.header, negotiatedMinor) || !validateCorrelation(value.correlation) || !validateEvent(value.event)) return false;\n\
  const envelope = value as unknown as EventEnvelope;\n\
  return validateEnvelopeDescriptor(envelope.header, envelope.correlation, envelope.event, \"event\", transferSlots);\n\
}\n",
    );
}

fn ts_primitive(value: Primitive) -> &'static str {
    match value {
        Primitive::U8 | Primitive::U16 | Primitive::U32 | Primitive::I32 => "number",
        Primitive::U64 => "bigint",
        Primitive::Bool => "boolean",
        Primitive::Bytes16 | Primitive::Bytes32 => "Uint8Array",
    }
}

fn ts_primitive_validator(value: Primitive, expression: &str) -> String {
    match value {
        Primitive::U8 => format!("isU8({expression})"),
        Primitive::U16 => format!("isU16({expression})"),
        Primitive::U32 => format!("isU32({expression})"),
        Primitive::U64 => format!("isU64({expression})"),
        Primitive::I32 => format!("isI32({expression})"),
        Primitive::Bool => format!("typeof {expression} === \"boolean\""),
        Primitive::Bytes16 => format!("isFixedBytes({expression}, 16)"),
        Primitive::Bytes32 => format!("isFixedBytes({expression}, 32)"),
    }
}

fn ts_type(value: &Type) -> String {
    match value {
        Type::Primitive(value) => ts_primitive(*value).into(),
        Type::Named(value) => value.clone(),
        Type::Optional(inner) => ts_type(inner),
        Type::List(inner, _) => format!("{}[]", ts_type(inner)),
        Type::Bytes(_) => "Uint8Array".into(),
    }
}

fn ts_validator(value: &Type, expression: &str) -> String {
    match value {
        Type::Primitive(value) => ts_primitive_validator(*value, expression),
        Type::Named(value) => format!("validate{value}({expression})"),
        Type::Optional(inner) => ts_validator(inner, expression),
        Type::List(inner, limit) => format!(
            "Array.isArray({expression}) && {expression}.length <= {limit} && {expression}.every((entry) => {})",
            ts_validator(inner, "entry")
        ),
        Type::Bytes(limit) => {
            format!("{expression} instanceof Uint8Array && {expression}.byteLength <= {limit}")
        }
    }
}

fn generate_desktop_registry(protocol: &Protocol, digest: &[u8; 32]) -> String {
    let mut out = String::new();
    writeln!(out, "# @generated by pdf-rs-protocol-codegen; DO NOT EDIT.").unwrap();
    writeln!(
        out,
        "registry {} {} {}",
        protocol.name, protocol.major, protocol.minor
    )
    .unwrap();
    writeln!(out, "generator_version {GENERATOR_VERSION}").unwrap();
    writeln!(out, "compatible_minor_min {}", protocol.minor).unwrap();
    writeln!(out, "schema_sha256 {}", lowercase_hex(digest)).unwrap();
    writeln!(out, "wire_schema_hash {}", lowercase_hex(&digest[..16])).unwrap();
    writeln!(out, "schema_hash_truncation {SCHEMA_HASH_TRUNCATION}").unwrap();
    writeln!(out, "byte_order little-endian").unwrap();
    writeln!(out, "header_bytes 20").unwrap();
    for (name, ty, offset, bytes) in [
        ("major", "u16", 0, 2),
        ("minor", "u16", 2, 2),
        ("message_type", "u16", 4, 2),
        ("flags", "u16", 6, 2),
        ("payload_len", "u32", 8, 4),
        ("sequence", "u64", 12, 8),
    ] {
        writeln!(out, "header_field {name} {ty} {offset} {bytes}").unwrap();
    }
    for scalar in &protocol.scalars {
        writeln!(
            out,
            "scalar {} {}",
            scalar.name,
            scalar.primitive.schema_name()
        )
        .unwrap();
    }
    for enumeration in &protocol.enums {
        writeln!(
            out,
            "enum {} {}",
            enumeration.name,
            enumeration.repr.schema_name()
        )
        .unwrap();
        for variant in &enumeration.variants {
            writeln!(
                out,
                "enum_variant {} {} {}",
                enumeration.name, variant.name, variant.tag
            )
            .unwrap();
        }
    }
    for record in &protocol.records {
        writeln!(out, "record {}", record.name).unwrap();
        for field in &record.fields {
            writeln!(
                out,
                "record_field {} {} {} {} {} {}",
                record.name,
                field.name,
                field.ty.schema_name(),
                if field.presence == Presence::Required {
                    "required"
                } else {
                    "optional"
                },
                match field.privacy {
                    Privacy::Public => "public",
                    Privacy::Private => "private",
                    Privacy::Sensitive => "sensitive",
                },
                type_limit(&field.ty)
            )
            .unwrap();
        }
    }
    for union in &protocol.unions {
        writeln!(out, "union {} {}", union.name, union.repr.schema_name()).unwrap();
        for variant in &union.variants {
            writeln!(
                out,
                "union_variant {} {} {}",
                union.name, variant.name, variant.tag
            )
            .unwrap();
            for field in &variant.fields {
                writeln!(
                    out,
                    "union_variant_field {} {} {} {} {} {}",
                    union.name,
                    variant.name,
                    field.name,
                    field.ty.schema_name(),
                    match field.privacy {
                        Privacy::Public => "public",
                        Privacy::Private => "private",
                        Privacy::Sensitive => "sensitive",
                    },
                    type_limit(&field.ty)
                )
                .unwrap();
            }
        }
    }
    if let Some(capabilities) = protocol
        .enums
        .iter()
        .find(|definition| definition.name == "EndpointCapability")
    {
        for variant in &capabilities.variants {
            writeln!(out, "endpoint_capability {} {}", variant.name, variant.tag).unwrap();
        }
    }
    for message in &protocol.messages {
        writeln!(
            out,
            "message {} {} {} {} {} {} {} {} {} {} {}",
            message.kind.schema_name(),
            message.id,
            message.name,
            message.payload,
            message.state,
            message.correlation,
            message.allowed_flags,
            message.min_transfer_slots,
            message.max_transfer_slots,
            message.max_payload_bytes,
            message.disposition
        )
        .unwrap();
        let record = protocol
            .records
            .iter()
            .find(|record| record.name == message.payload)
            .expect("validated payload");
        for field in &record.fields {
            writeln!(
                out,
                "field {} {} {} {} {} {}",
                message.id,
                field.name,
                field.ty.schema_name(),
                if field.presence == Presence::Required {
                    "required"
                } else {
                    "optional"
                },
                match field.privacy {
                    Privacy::Public => "public",
                    Privacy::Private => "private",
                    Privacy::Sensitive => "sensitive",
                },
                type_limit(&field.ty)
            )
            .unwrap();
        }
        for outcome in &message.outcomes {
            let id = protocol
                .messages
                .iter()
                .find(|candidate| {
                    candidate.kind == MessageKind::Event && candidate.name == *outcome
                })
                .expect("validated outcome")
                .id;
            writeln!(out, "outcome {} {}", message.id, id).unwrap();
        }
    }
    out
}

fn generate_hash_registry(digest: &[u8; 32]) -> String {
    format!(
        "algorithm sha256\ngenerator_version {GENERATOR_VERSION}\ncanonical_source protocol/engine.protocol\nfull_sha256 {}\nwire_hash {}\nwire_hash_bytes 16\ntruncation_policy {SCHEMA_HASH_TRUNCATION}\n",
        lowercase_hex(digest),
        lowercase_hex(&digest[..16])
    )
}

fn generate_compatibility_vectors(protocol: &Protocol, digest: &[u8; 32]) -> String {
    let full = lowercase_hex(digest);
    let wire = lowercase_hex(&digest[..16]);
    let minimum_minor = protocol.minor;
    let mut fork_hash = digest[..16].to_vec();
    fork_hash[0] ^= 0xff;
    let fork_wire = lowercase_hex(&fork_hash);
    let mut vectors = vec![format!(
        "    {{\"name\":\"exact-schema\",\"local_major\":{},\"local_minor\":{},\"peer_major\":{},\"peer_minor\":{},\"peer_schema_hash\":\"{wire}\",\"peer_supported\":\"0x3f\",\"peer_mandatory\":\"0x00\",\"expected\":\"ExactSchema\"}}",
        protocol.major, protocol.minor, protocol.major, protocol.minor
    )];
    if protocol.minor > 0 {
        vectors.push(format!(
            "    {{\"name\":\"unregistered-older-minor\",\"local_major\":{},\"local_minor\":{},\"peer_major\":{},\"peer_minor\":{},\"peer_schema_hash\":\"11111111111111111111111111111111\",\"peer_supported\":\"0x3f\",\"peer_mandatory\":\"0x00\",\"expected_error\":\"UnsupportedMinor\"}}",
            protocol.major,
            protocol.minor,
            protocol.major,
            protocol.minor - 1
        ));
    }
    if protocol.minor < u16::MAX {
        vectors.push(format!(
            "    {{\"name\":\"future-minor\",\"local_major\":{},\"local_minor\":{},\"peer_major\":{},\"peer_minor\":{},\"peer_schema_hash\":\"{fork_wire}\",\"peer_supported\":\"0x3f\",\"peer_mandatory\":\"0x00\",\"expected_error\":\"UnsupportedMinor\"}}",
            protocol.major,
            protocol.minor,
            protocol.major,
            protocol.minor + 1
        ));
    }
    vectors.extend([
        format!(
            "    {{\"name\":\"same-minor-schema-fork\",\"local_major\":{},\"local_minor\":{},\"peer_major\":{},\"peer_minor\":{},\"peer_schema_hash\":\"{fork_wire}\",\"peer_supported\":\"0x3f\",\"peer_mandatory\":\"0x00\",\"expected_error\":\"IncompatibleSchema\"}}",
            protocol.major, protocol.minor, protocol.major, protocol.minor
        ),
        format!(
            "    {{\"name\":\"unknown-optional-capability\",\"local_major\":{},\"local_minor\":{},\"peer_major\":{},\"peer_minor\":{},\"peer_schema_hash\":\"{wire}\",\"peer_supported\":\"0x800000000000003f\",\"peer_mandatory\":\"0x00\",\"expected\":\"ExactSchema\"}}",
            protocol.major, protocol.minor, protocol.major, protocol.minor
        ),
        format!(
            "    {{\"name\":\"unknown-mandatory-capability\",\"local_major\":{},\"local_minor\":{},\"peer_major\":{},\"peer_minor\":{},\"peer_schema_hash\":\"{wire}\",\"peer_supported\":\"0x3f\",\"peer_mandatory\":\"0x8000000000000000\",\"expected_error\":\"UnknownMandatoryCapability\"}}",
            protocol.major, protocol.minor, protocol.major, protocol.minor
        ),
        format!(
            "    {{\"name\":\"mandatory-not-supported-by-endpoint\",\"local_major\":{},\"local_minor\":{},\"peer_major\":{},\"peer_minor\":{},\"peer_schema_hash\":\"{wire}\",\"peer_supported\":\"0x3e\",\"peer_mandatory\":\"0x01\",\"expected_error\":\"InvalidEndpointCapabilities\"}}",
            protocol.major, protocol.minor, protocol.major, protocol.minor
        ),
        format!(
            "    {{\"name\":\"major-mismatch\",\"local_major\":{},\"local_minor\":{},\"peer_major\":{},\"peer_minor\":{},\"peer_schema_hash\":\"{wire}\",\"peer_supported\":\"0x3f\",\"peer_mandatory\":\"0x00\",\"expected_error\":\"UnsupportedMajor\"}}",
            protocol.major,
            protocol.minor,
            if protocol.major == u16::MAX {
                protocol.major - 1
            } else {
                protocol.major + 1
            },
            protocol.minor
        ),
    ]);
    format!(
        "{{\n  \"generator_version\": \"{GENERATOR_VERSION}\",\n  \"schema_sha256\": \"{full}\",\n  \"wire_schema_hash\": \"{wire}\",\n  \"truncation_policy\": \"{SCHEMA_HASH_TRUNCATION}\",\n  \"minimum_compatible_minor\": {minimum_minor},\n  \"vectors\": [\n{}\n  ]\n}}\n",
        vectors.join(",\n")
    )
}

fn generate_invalid_vectors(protocol: &Protocol, digest: &[u8; 32]) -> String {
    let hello = protocol
        .messages
        .iter()
        .find(|message| message.name == "Hello")
        .expect("canonical schema has Hello");
    let header = desktop_header_hex(protocol.major, protocol.minor, hello.id, 0, 0, 1);
    let zero_sequence = desktop_header_hex(protocol.major, protocol.minor, hello.id, 0, 0, 0);
    format!(
        "{{\n  \"generator_version\": \"{GENERATOR_VERSION}\",\n  \"schema_sha256\": \"{}\",\n  \"vectors\": [\n    {{\"name\":\"truncated-header\",\"frame_hex\":\"{}\",\"transfer_slots\":0,\"expected_error\":\"TruncatedHeader\"}},\n    {{\"name\":\"payload-length-mismatch\",\"frame_hex\":\"{}00\",\"transfer_slots\":0,\"expected_error\":\"FrameLengthMismatch\"}},\n    {{\"name\":\"zero-sequence\",\"frame_hex\":\"{}\",\"transfer_slots\":0,\"expected_error\":\"NonMonotonicSequence\"}},\n    {{\"name\":\"unknown-message\",\"message_type\":65535,\"expected_error\":\"UnknownMessage\"}},\n    {{\"name\":\"unsupported-flags\",\"message_type\":{},\"flags\":1,\"expected_error\":\"InvalidFlags\"}},\n    {{\"name\":\"missing-required-correlation\",\"message_type\":{},\"correlation\":{{}},\"expected_error\":\"InvalidCorrelation\"}},\n    {{\"name\":\"transfer-count-out-of-range\",\"message_type\":{},\"transfer_slots\":1,\"expected_error\":\"InvalidTransferCount\"}},\n    {{\"name\":\"provide-data-duplicate-slot\",\"message_type\":4,\"transfer_slots\":2,\"slots\":[0,0],\"expected_error\":\"InvalidTransferBinding\"}},\n    {{\"name\":\"surface-stride-too-small\",\"width\":100,\"height\":1,\"stride\":1,\"byte_length\":\"1\",\"expected_error\":\"InvalidSurfaceLayout\"}},\n    {{\"name\":\"surface-range-overflow\",\"byte_offset\":\"18446744073709551615\",\"byte_length\":\"1\",\"region_length\":\"18446744073709551615\",\"expected_error\":\"NumericOverflow\"}},\n    {{\"name\":\"surface-reclaimed-missing-reason\",\"message_type\":113,\"payload\":{{\"surface\":1}},\"expected_error\":\"MissingRequiredField\"}},\n    {{\"name\":\"unknown-mandatory-capability\",\"mandatory\":\"0x8000000000000000\",\"expected_error\":\"UnknownMandatoryCapability\"}},\n    {{\"name\":\"mandatory-not-supported-by-endpoint\",\"supported\":\"0x3e\",\"mandatory\":\"0x01\",\"expected_error\":\"InvalidEndpointCapabilities\"}},\n    {{\"name\":\"silent-decision-truncation\",\"missing_total\":17,\"missing_count\":16,\"missing_completeness\":\"Complete\",\"expected_error\":\"InvalidCapabilityDecision\"}}\n  ]\n}}\n",
        lowercase_hex(digest),
        &header[..18],
        header,
        zero_sequence,
        hello.id,
        hello.id,
        hello.id
    )
}

fn desktop_header_hex(
    major: u16,
    minor: u16,
    message_type: u16,
    flags: u16,
    payload_len: u32,
    sequence: u64,
) -> String {
    let mut bytes = Vec::new();
    bytes.extend_from_slice(&major.to_le_bytes());
    bytes.extend_from_slice(&minor.to_le_bytes());
    bytes.extend_from_slice(&message_type.to_le_bytes());
    bytes.extend_from_slice(&flags.to_le_bytes());
    bytes.extend_from_slice(&payload_len.to_le_bytes());
    bytes.extend_from_slice(&sequence.to_le_bytes());
    lowercase_hex(&bytes)
}

#[cfg(test)]
mod tests {
    use super::{generate_compatibility_vectors, generated_files};
    use crate::parser::parse_schema;
    use std::path::Path;

    const SCHEMA: &str = include_str!("../../../protocol/engine.protocol");

    #[test]
    fn generation_is_byte_deterministic_and_complete() {
        let protocol = parse_schema(SCHEMA).unwrap();
        let first = generated_files(&protocol, SCHEMA);
        let second = generated_files(&protocol, SCHEMA);
        assert_eq!(first, second);
        assert_eq!(first.len(), 6);
        for required in [
            "runtime/protocol/src/generated.rs",
            "platform/browser/generated/engine-protocol.ts",
            "platform/desktop/generated/engine-protocol.registry",
            "protocol/generated/compatibility-vectors.json",
            "protocol/generated/invalid-vectors.json",
        ] {
            assert!(
                first
                    .iter()
                    .any(|file| file.relative_path == Path::new(required))
            );
        }
    }

    #[test]
    fn compatibility_replay_has_stable_outcomes() {
        let protocol = parse_schema(SCHEMA).unwrap();
        let vectors = generate_compatibility_vectors(&protocol, &[0x5a; 32]);
        assert!(vectors.contains("\"expected\":\"ExactSchema\""));
        assert!(!vectors.contains("\"expected\":\"CompatibleMinor\""));
        assert!(vectors.contains("\"generator_version\": \"0.1.0\""));
        assert!(vectors.contains("\"minimum_compatible_minor\": 2"));
        assert!(vectors.contains("\"name\":\"unregistered-older-minor\""));
        assert!(vectors.contains("\"name\":\"future-minor\""));
        assert!(vectors.contains("\"name\":\"same-minor-schema-fork\""));
        assert!(vectors.contains("\"peer_schema_hash\""));
        assert!(vectors.contains("\"expected_error\":\"UnknownMandatoryCapability\""));
        assert!(vectors.contains("\"expected_error\":\"InvalidEndpointCapabilities\""));
    }

    #[test]
    fn invalid_correlation_vector_replays_against_generated_shape() {
        let protocol = parse_schema(SCHEMA).unwrap();
        let hello = protocol
            .messages
            .iter()
            .find(|message| message.name == "Hello")
            .unwrap();
        let requirements = super::correlation_shape(&hello.correlation);
        assert!(
            [
                requirements.0,
                requirements.1,
                requirements.2,
                requirements.3
            ]
            .into_iter()
            .any(|requirement| requirement == "Required"),
            "the empty correlation vector must be rejected"
        );
        let vectors = super::generate_invalid_vectors(&protocol, &[0x5a; 32]);
        assert!(vectors.contains("\"correlation\":{}"));
    }

    #[test]
    fn output_path_guard_rejects_parent_and_absolute_paths() {
        assert!(super::reject_symlink_path(Path::new("."), Path::new("../escape")).is_err());
        assert!(super::reject_symlink_path(Path::new("."), Path::new("/absolute")).is_err());
    }
}
