// Generated by scripts/generate-native-worker-abi.mjs. Do not edit.

export const NATIVE_WORKER_ABI_VERSION = 1;
export const NATIVE_WORKER_ABI_SHA256 = "08695f58916d714c81d952a8bded1a926c5e539501d51fbd6a0b1e94c96121d6";
export const NATIVE_WORKER_ABI_HASH_WORDS = Object.freeze([
  0x585f6908,
  0x4c716d91,
  0xa852d981,
  0x921aedbd,
  0x95535e6c,
  0xbd1fd501,
  0x941e0b6a,
  0xd62161c9,
] as const);
export const NATIVE_WORKER_FUNCTION_SIGNATURES = Object.freeze({
  "pdf_rs_worker_prepare_input": "(i32)->i32",
  "pdf_rs_worker_prepare_transfer": "(i32,i32)->i32",
  "pdf_rs_worker_dispatch": "(i32,i32)->i32",
  "pdf_rs_worker_poll": "()->i32",
  "pdf_rs_worker_output_pointer": "()->i32",
  "pdf_rs_worker_output_length": "()->i32",
  "pdf_rs_worker_transfer_count": "()->i32",
  "pdf_rs_worker_transfer_pointer": "(i32)->i32",
  "pdf_rs_worker_transfer_length": "(i32)->i32",
  "pdf_rs_worker_memory_epoch": "()->i32",
  "pdf_rs_worker_shutdown": "()->i32",
  "pdf_rs_worker_abi_version": "()->i32",
  "pdf_rs_worker_abi_hash_0": "()->i32",
  "pdf_rs_worker_abi_hash_1": "()->i32",
  "pdf_rs_worker_abi_hash_2": "()->i32",
  "pdf_rs_worker_abi_hash_3": "()->i32",
  "pdf_rs_worker_abi_hash_4": "()->i32",
  "pdf_rs_worker_abi_hash_5": "()->i32",
  "pdf_rs_worker_abi_hash_6": "()->i32",
  "pdf_rs_worker_abi_hash_7": "()->i32",
  "main": "(i32,i32)->i32",
} as const);
