// Generated by scripts/generate-native-worker-abi.mjs. Do not edit.

export const NATIVE_WORKER_ABI_VERSION = 2;
export const NATIVE_WORKER_ABI_SHA256 = "97b5098eaed69c9ca375c31325911613952aae4c549311e63d5ded56f6374bae";
export const NATIVE_WORKER_ABI_HASH_WORDS = Object.freeze([
  0x8e09b597,
  0x9c9cd6ae,
  0x13c375a3,
  0x13169125,
  0x4cae2a95,
  0xe6119354,
  0x56ed5d3d,
  0xae4b37f6,
] as const);
export const NATIVE_WORKER_STATUS_OK = 0;
export const NATIVE_WORKER_STATUS_REJECTED = 0xfffe;
// Reserved for unwind-capable/internal builds. Production panic=abort traps.
export const NATIVE_WORKER_STATUS_INTERNAL_UNWIND = 0xffff;
export const NATIVE_WORKER_POLL_OUTPUT = 1;
export const NATIVE_WORKER_POLL_PENDING = 2;
export const NATIVE_WORKER_POLL_MASK = 3;
export const NATIVE_WORKER_FUNCTION_SIGNATURES = Object.freeze({
  "pdf_rs_worker_initialize": "(i32,i32,i32,i32,i32)->i32",
  "pdf_rs_worker_prepare_input": "(i32)->i32",
  "pdf_rs_worker_prepare_transfer": "(i32,i32)->i32",
  "pdf_rs_worker_dispatch": "(i32,i32)->i32",
  "pdf_rs_worker_poll": "()->i32",
  "pdf_rs_worker_output_pointer": "()->i32",
  "pdf_rs_worker_output_length": "()->i32",
  "pdf_rs_worker_transfer_count": "()->i32",
  "pdf_rs_worker_transfer_pointer": "(i32)->i32",
  "pdf_rs_worker_transfer_length": "(i32)->i32",
  "pdf_rs_worker_memory_epoch": "()->i32",
  "pdf_rs_worker_shutdown": "()->i32",
  "pdf_rs_worker_abi_version": "()->i32",
  "pdf_rs_worker_abi_hash_0": "()->i32",
  "pdf_rs_worker_abi_hash_1": "()->i32",
  "pdf_rs_worker_abi_hash_2": "()->i32",
  "pdf_rs_worker_abi_hash_3": "()->i32",
  "pdf_rs_worker_abi_hash_4": "()->i32",
  "pdf_rs_worker_abi_hash_5": "()->i32",
  "pdf_rs_worker_abi_hash_6": "()->i32",
  "pdf_rs_worker_abi_hash_7": "()->i32",
  "main": "(i32,i32)->i32",
} as const);
