use std::fs;
use std::path::{Path, PathBuf};

use pdf_rs_protocol::{SCHEMA_HASH, SCHEMA_HASH_TRUNCATION, SCHEMA_SHA256_HEX};

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root is readable")
}

#[test]
fn product_crate_is_dependency_free_and_generated_schema_has_one_owner() {
    let root = repository_root();
    let manifest =
        fs::read_to_string(root.join("runtime/protocol/Cargo.toml")).expect("manifest is readable");
    let library =
        fs::read_to_string(root.join("runtime/protocol/src/lib.rs")).expect("lib is readable");
    let generated = fs::read_to_string(root.join("runtime/protocol/src/generated.rs"))
        .expect("generated Rust registry is readable");

    assert!(manifest.contains("[dependencies]\n"));
    let dependencies = manifest
        .split_once("[dependencies]\n")
        .expect("dependencies table exists")
        .1;
    assert!(
        dependencies.trim().is_empty(),
        "protocol product crate must have zero dependencies"
    );
    assert!(library.contains("#![forbid(unsafe_code)]"));
    assert!(library.contains("#![deny(missing_docs)]"));
    assert!(library.contains("#[rustfmt::skip]\nmod generated;"));
    assert!(library.contains("mod generated;"));
    assert!(library.contains("pub use generated::*;"));
    assert!(generated.starts_with("// @generated by pdf-rs-protocol-codegen; DO NOT EDIT.\n"));
    assert!(generated.contains("// Source: protocol/engine.protocol\n"));
    assert!(generated.contains("#![allow(missing_docs)]"));

    for entry in fs::read_dir(root.join("runtime/protocol/src")).expect("source directory exists") {
        let path = entry.expect("source entry is readable").path();
        if path.extension().and_then(|value| value.to_str()) != Some("rs")
            || path.file_name().and_then(|value| value.to_str()) == Some("generated.rs")
        {
            continue;
        }
        let source = fs::read_to_string(&path).expect("handwritten source is readable");
        assert!(
            !source.contains("pub struct EnvelopeHeader")
                && !source.contains("pub struct ProtocolHello")
                && !source.contains("pub enum SurfaceTransport")
                && !source.contains("pub enum Command")
                && !source.contains("pub enum Event"),
            "{} must not hand-maintain generated wire definitions",
            path.display()
        );
    }
}

#[test]
fn generated_hash_registry_matches_the_exported_wire_constants() {
    let registry = fs::read_to_string(repository_root().join("protocol/generated/schema-hash.txt"))
        .expect("generated hash registry is readable");
    let wire_hash = SCHEMA_HASH
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    for expected in [
        "algorithm sha256".to_owned(),
        "canonical_source protocol/engine.protocol".to_owned(),
        format!("full_sha256 {SCHEMA_SHA256_HEX}"),
        format!("wire_hash {wire_hash}"),
        "wire_hash_bytes 16".to_owned(),
        format!("truncation_policy {SCHEMA_HASH_TRUNCATION}"),
    ] {
        assert!(
            registry.lines().any(|line| line == expected.as_str()),
            "generated hash registry is missing {expected:?}"
        );
    }
}

#[test]
fn handwritten_product_sources_have_no_io_process_or_unsafe_escape_hatch() {
    let root = repository_root();
    for entry in fs::read_dir(root.join("runtime/protocol/src")).expect("source directory exists") {
        let path = entry.expect("source entry is readable").path();
        if path.extension().and_then(|value| value.to_str()) != Some("rs")
            || path.file_name().and_then(|value| value.to_str()) == Some("generated.rs")
        {
            continue;
        }
        let source = fs::read_to_string(&path).expect("handwritten source is readable");
        for forbidden in [
            "std::fs",
            "std::net",
            "std::process",
            "extern crate",
            "unsafe {",
            "unsafe fn",
        ] {
            assert!(
                !source.contains(forbidden),
                "{} contains forbidden product boundary {forbidden:?}",
                path.display()
            );
        }
    }
}

#[test]
fn provenance_declares_validation_order_and_redaction_boundary() {
    let provenance = fs::read_to_string(repository_root().join("runtime/protocol/PROVENANCE.md"))
        .expect("provenance is readable");
    for required in [
        "src/generated.rs",
        "fixed header",
        "message descriptor",
        "transfer count",
        "correlation",
        "Surface",
        "checked arithmetic",
        "never appear in `Debug`, `Display`",
        "must not maintain a second command, event, or field registry",
    ] {
        assert!(
            provenance.contains(required),
            "protocol provenance is missing {required:?}"
        );
    }
}
